# Generated by Django 5.2 on 2025-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('short_description', models.CharField(max_length=55)),
                ('banar_image', models.ImageField(upload_to='bannar/')),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
