# Generated by Django 5.2 on 2025-04-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
