# Generated by Django 5.2 on 2025-05-11 09:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_latestproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chooseus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
